package com.storeit.storeit.protocol;

import java.util.ArrayList;

/**
 * StoreIt file object
 * Will be generated by the FileManager :D
 */
public class StoreitFile {

    private String path;
    private String unique_hash;
    private String metadata;
    private int kind;
    private ArrayList<StoreitFile> files;

    public StoreitFile(String path, String unique_hash, int kind) {
        this.path = path;
        this.unique_hash = unique_hash;
        this.kind = kind;
        this.metadata = "";
        this.files = new ArrayList<>();
    }

    public String getPath() {
        return path;
    }

    public ArrayList<StoreitFile> getFiles() {
        return files;
    }

    public void addFile(StoreitFile file) {
        this.files.add(file);
    }



    public String getUnique_hash() {
        return unique_hash;
    }

    public String getMetadata(){
        return metadata;
    }

    public int getKind() {
        return kind;
    }

    public void setKind(int kind) {
        this.kind = kind;
    }
}
