package com.storeit.storeit.protocol;

import android.net.Uri;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * StoreIt file object
 * Will be generated by the FileManager :D
 */
public class StoreitFile {

    private String path;
    private String unique_hash;
    private String metadata;
    private int kind;
    private HashMap<String, StoreitFile> files;

    public StoreitFile(String path, String unique_hash, int kind) {
        this.path = path;
        this.unique_hash = unique_hash;
        this.kind = kind;
        this.metadata = "";
        this.files = new HashMap<>();
    }

    public String getPath() {
        return path;
    }

    public HashMap<String, StoreitFile> getFiles() {
        return files;
    }

    public void addFile(StoreitFile file) {
        Uri uri = Uri.parse(file.getPath());
        this.files.put(uri.getLastPathSegment(), file);
    }

    public String getUnique_hash() {
        return unique_hash;
    }

    public String getMetadata(){
        return metadata;
    }

    public int getKind() {
        return kind;
    }

    public void setKind(int kind) {
        this.kind = kind;
    }
}
