# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'StoreIt' do
	pod 'ObjectMapper', '~> 1.1'
    pod 'TCPIP', '~> 0.1'
    #pod 'SwiftSockets', '~> 0.20'
    #pod 'CocoaAsyncSocket'
end

target 'StoreItTests' do

end

target 'StoreItUITests' do

end

